name: farinwatatv
description: Farinwata TV Shakallo

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.3
  scoped_model: ^1.1.0
  flutter_svg: ^0.22.0
  line_icons: ^2.0.1
  responsive_navigation_bar: ^2.1.1
  carousel_slider: ^4.0.0
  flutter_swiper: ^1.1.6
  meedu_player: ^0.4.3
  wakelock: ^0.5.2
  dio: ^4.0.0
  youtube_player_flutter: ^8.0.0
  timeago: ^3.1.0
  intl: ^0.17.0
  flutter_inappwebview: ^5.3.2
  flutter_slider_drawer: ^2.0.0
  sqflite: ^2.0.0+3
  youtube_explode_dart: ^1.9.9
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  fonts:
    - family: Kaushan Script
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Bad Script
      fonts:
        - asset: assets/fonts/BadScript-Regular.ttf
    - family: Oleo Script
      fonts:
        - asset: assets/fonts/OleoScript-Bold.ttf
        - asset: assets/fonts/OleoScript-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Merienda One
      fonts:
        - asset: assets/fonts/MeriendaOne-Regular.ttf